### PR TITLE
Intl4x API refactorings.

### LINKED ISSUE #1027: Numeric Collation option does not work.
```dart

    final i = Intl(locale: Locale.parse('en-US'));
    final c = i.collation(CollationOptions(numeric: true));
    final lis = ['0', '1', '2', '10'];
    lis.sort((left, right) => c.compare(left, right));
    log('$lis');

```
[log] [0, 1, 10, 2]

Numeric collation option does not work.

from collation_4x.dart
```dart

extension on icu.Locale {
  void setOptions(CollationOptions options) {
    final icuNumeric = switch (options.numeric) {
      true => icu.CollatorNumericOrdering.on,
      false => icu.CollatorNumericOrdering.off,
      null => null,
    };
    if (icuNumeric != null &&
        getUnicodeExtension(_numericExtensionKey) != null) {
      setUnicodeExtension(_numericExtensionKey, icuNumeric.name); <-- HERE 
    }
}

```

'on' and 'off' do not work.

'true' and 'false' works.

### PR DESCRIPTION
**Pull request by mosuem**
General API refactorings.

- Getting rid of the `Intl` object, as it only served as a wrapper of `Locale`. So the `...Format` objects are now the top-level things.
- Remove most `...Options` objects from the public API, as they make it more verbose. Users now directly input the options to the top-level `...Format` constructor.
- Use `=>` instead of block bodies for methods where possible.
- Fix some imports
- Add documentation to some classes (more to follow!)
- Remove some methods which are not implemented in ICU4X
- Add conformance testing between ICU4X and ECMA for `DateTime` formatting. This shows many discrepancies for now, which need to be resolved before this PR can be merged - or we need to decide they are fine and remove the conformance testing.

Fixes #1027

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.

**Note**: The Dart team is trialing Gemini Code Assist. Don't take its comments as final Dart team feedback. Use the suggestions if they're helpful; otherwise, wait for a human reviewer.

</details>

### CODE REVIEW

File: pkgs/intl4x/lib/collation.dart [hunk 1]
```diff
@@ -2,16 +2,18 @@
 // for details. All rights reserved. Use of this source code is governed by a
 // BSD-style license that can be found in the LICENSE file.
 
-import 'intl4x.dart';
+import 'collation.dart' show Collation;
```
[the remark this answers is not in the document]
Comment (robertbastian) [reply pkgs/intl4x/lib/collation.dart]: .

File: pkgs/intl4x/test/collation_test.dart
Comment (robertbastian) [inline pkgs/intl4x/test/collation_test.dart]: also test the string extension method

File: pkgs/intl4x/lib/src/options.dart [hunk 2]
```diff
@@ -28,4 +26,29 @@ enum Calendar {
   const Calendar([this._jsName]);
 }
 
+enum NumberingSystem {
+  arab,
```
Comment (robertbastian) [inline pkgs/intl4x/lib/src/options.dart]: suggestion: these should be spelled out instead of using the codes. use the English names from CLDR: https://github.com/unicode-org/cldr/blob/b91d8c77194d73c516dd07fe910dc6a29411be13/common/main/en.xml#L720-L938
