### PR TITLE
Fix `yy` parsing

### LINKED ISSUE #483: FormatException on specific date and time (very strange)
**Describe the bug**
Getting the following exception on this specific date range only i.e. **23-03-12 02:00:00** to **23-03-12 02:59:59** with the following message

_FormatException: Error parsing 23-03-12 02:00:00, invalid hour value: 2 in en_US with time zone offset -4:00:00.000000. Expected value between 3 and 3. Date parsed as 0023-03-12 03:00:00.000.._

**To Reproduce**
The timezone should be either UTC -4, -5, -6, -7 and running a local test as following will reproduce it. Please note that this works fine for all the time windows except **02:00:00 till 02:59:59** 
```
void main(List<String> arguments) {
    String date = "23-03-12 02:00:00";
    DateTime? dateTime = DateFormat('y-MM-dd HH:mm:ss').parseStrict(date).toLocal();
}
```

**Expected**
The library should work as expected on the above mentioned time range.

### PR DESCRIPTION
**Pull request by mosuem**
Fix #483.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

File: pkgs/intl/lib/src/intl/date_builder.dart [hunk 1]
```diff
@@ -181,12 +183,31 @@ class DateBuilder {
...
+      _date = preliminaryResult;
+    } else {
+      _date = _correctForErrors(preliminaryResult, retries);
+    }
+    return _date!;
+  }
 
-    DateTime preliminaryResult;
-    final hasCentury = !_hasAmbiguousCentury || year < 0 || year >= 100;
+  int getEstimatedYear() {
```
Comment (lrhn) [inline pkgs/intl/lib/src/intl/date_builder.dart:197]: Should be a getter, an should not start with `get`.
Should probably not be public at all. (It's not documented, big hint that it's probably private.)

File: pkgs/intl/lib/src/intl/date_builder.dart [hunk 2]
```diff
@@ -27,6 +27,8 @@ class DateBuilder {
   /// Ignored if `year < 0` or `year >= 100`.
   bool _hasAmbiguousCentury = false;
 
+  bool get hasCentury => !_hasAmbiguousCentury || year < 0 || year >= 100;
```
Comment (lrhn) [inline pkgs/intl/lib/src/intl/date_builder.dart:30]: I assume this comes from an ambiguity in parsing a two-digit year.

Do we really *need* to expose the this flag?
Is it something the user can act on at all?
That is: Should it be private?

The builder should produe a single date. Which date it produces is all that matters. The client shouldn't care whether it has a century or not, it should just put data into the builder, using its best effort, and use what comes out.


I see that there is an `setHasAmbiguousCentury` method.
(Which should probably have been a setter.)

So we are leaking the concept in the API already.

**Review by lrhn — APPROVED** [review]
LGTM!
